version: "3.1"
services:
    gateway:
        ports:
            - 1000:1000
        working_dir: /
        expose:
            - "1000"
        build:
            context: ./gateway
        depends_on:
            - films
            - directors
    frontend:
        ports:
            - 4200:80
        working_dir: /
        expose:
            - "80"
        build:
            context: ./nginx
        depends_on:
            - gateway
    films:
        working_dir: /
        build:
            context: ./services/films
    directors:
        working_dir: /
        build:
            context: ./services/directors